### ISSUE TITLE
Thw linear probing

### ISSUE THREAD

**Issue by CASlzwde** [TonyLianLong/CrossMAE#4]
Hi， this is an interesting work. I want to know the linear probing results.

**Comment by Max-Fu** [comment]
The linear probe results for ViT-S and ViT-B are provided below. All models are pretrained for 800 epochs. 

For ViT-S:
| MAE | CrossMAE| 
| -- | -- | 
| 49.7 | 51.5 | 

For ViT-B:
| MAE | CrossMAE |
| -- | -- |
| 65.1 | 65.4 |
