### ISSUE TITLE
Inference output result with color distortion

### ISSUE THREAD

**Issue by ksksjsjs** [TonyLianLong/CrossMAE#5]
Using imagenet-ma-cross vitb-pretrain-wfm-mr0.75-kmr0.75-dd12-ep800-ui.th weights, after loading the image for inference, it was found that the output contour of the image was roughly correct, but the color was distorted
![crossmae_reconstructed_image](https://github.com/user-attachments/assets/b0cea0e5-4053-4236-8e12-1445aff688f0)
This is the original image
![test_image_1](https://github.com/user-attachments/assets/1f891382-60d6-4ae9-95a7-837e6eb7693c)

How should this be resolved. If there are any inaccuracies in my expression, please raise them

**Comment by Max-Fu** [comment]
Hi, 

The patch values have to be unnormalized by the patch statistics. We will release a visualization script sometime this week / next week.

**Comment by Max-Fu** [comment]
Hi, 

Please check out the demo here: [cross_mae_visualize.ipynb](https://github.com/TonyLianLong/CrossMAE/blob/main/demo/cross_mae_visualize.ipynb)

Feel free to reopen this if there's more questions!
